# Problema 15
## 15)

Resolvamos un sistema de $N$ ecuaciones inhomogéneas con $N$ incógnitas vía **Descomposición LU**: <br>
<center> $A \cdot x = c$ </center> <br>
Para nuestro código, el sistema será tal que $A$ es una matriz $NxN$ y $c$ será $N\text{x}1$. Ambas las rellenaremos con números aletorios, pidiendo $N=4$:

In [1]:
#(descomposición LU): Quiero resolver A*x = c

n = parse(Int64, readline()) #Dim de la matriz: A = NxN

stdin>  4


4

In [2]:
A = rand(Int8,(n,n)) ./ 8 #Matriz a descomponer
c = rand(Int8,n) ./ 8 #inhomogeneidad

display(A)
display(c)

#Particularmente pedimos rellenar las matrices con randoms enteros pequeños, pero tranquilamente puede ser cualquier número

4×4 Matrix{Float64}:
 -3.625    7.375   9.25   -14.5
 -9.875  -15.5     5.125    0.75
 -8.75     9.625  -9.75     6.375
 11.375   -4.25   -4.5      0.125

4-element Vector{Float64}:
  1.875
  1.75
  9.5
 14.0

In [3]:
function LU(A=A,c=c,n=n) 
    L = zeros(Float64, (n,n))
    U = zeros(Float64, (n,n)) #creamos las matrices vacías L y U

    for i in 1:n
        L[i,1] = A[i,1] #escribimos la 1º columna de L
    end

    for j in 1:n
        U[1,j] = A[1,j]/A[1,1] #escribimos la 1º fila de U
    end

    for k in 2:n #k-ésima columna/fila (exceptuando la 1º)
        for i in k:n #rellenar la i-ésima fila
            local S 
            S = 0
            for j in 1:k-1 #loop de la sumatoria para columnas.  
                S += L[i,j]*U[j,k]
            end
            L[i,k] = A[i,k] - S #encuentro el elemento L_ik
        end

        for i in k:n #rellenar la i-ésima columna. Recordar que el algortimo va como 1º col -> 1º fila -> 2º col -> 2º fila -> ...
            local Z
            Z = 0
            for m in 1:k-1 #loop de la sumatoria para filas.
                Z += L[k,m]*U[m,i]
            end
            U[k,i] = (A[k,i] - Z)/L[k,k] #encuentro el elemento U_ki
        end
    end
    
    #Acá comprobamos que L y U están bien, seguimos...
    
    #Resuelvo L * z = c:

    z = zeros(n) #lista vacía de las n componentes de z
    z[1] = c[1]/L[1,1] #1º lugar =/= 0

    for i in range(2,n) #completar los demás espacios de z ;  # Re contra vale poner range() así en vez de trasladarlo a "1:n".
        local S
        S = 0
        for k in range(1,i-1) #loop para la sumatoria
            S += L[i,k]*z[k]

        end

        z[i] = (c[i] - S)/L[i,i]

    end #Comprobando en otra calc, da exactamente el mismo z, which is good

    #Resuelvo U * x = z:

    x = zeros(n) #lista vacía de las n componentes de x
    x[n] = z[n] #nº lugar =/= 0 (comparten el "último lugar" las soluciones z y x)

    for i in range(1,n-1) #completar los demás espacios de x "backwards" (por eso los n-i)
        local S
        S = 0
        for k in range(n-i,n)
            S += U[n-i,k]*x[k] #¿?
        end

        x[n-i] = z[n-i] - S
    end  
    
    return x
end

LU (generic function with 4 methods)

In [6]:
LU()

4-element Vector{Float64}:
 -0.46648847155380724
 -1.0589216304198772
 -3.365142273492371
 -2.6980063686047226

Verificando con una calculadora de matrices, vemos que efectivamente el resultado es el correcto.